language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "pypy"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -r py3_requirements.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then pip install -r requirements.txt; fi
script:
    - nosetests --with-coverage --cover-package=testtube
after_success:
    coveralls
